name: basic_functional_dart
description: A minimal functional library written entirely in dart.
version: 1.1.1
# homepage: https://www.example.com
repository: https://github.com/lgirolimetto/functional_dart

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
#  path: ^1.7.0
  fast_immutable_collections: ^10.2.2

dev_dependencies:
  #pedantic: ^1.9.0
  test: ^1.14.4

